name: actions
run-name: ${{ github.actor }} lance le test de compilation
on: [push]
jobs:
  compile-projet:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - run: cd projet && mvn clean compile
  # exemple (ne pas supprimé)
  #nom-du-job:
  #  runs-on: image-os
  #  steps:
  #    - uses: actions/checkout@v4  #Ne pas changer ça 
  #    - uses: actions/setup-node@v4
  #      with:
  #        node-version: '20'       # Précise sur quelle version de java le test est effectué
  #    - run: une commande          # Commande qui lance tout les tests unitaire
  #    - run: une autre commande    # 
