name: actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  compile-projet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '17'
      - run: cd projet
      - run: mvn clean compile
  # exemple (ne pas supprimé)
  #nom-du-job:
  #  runs-on: image-os
  #  steps:
  #    - uses: actions/checkout@v4  #Ne pas changer ça 
  #    - uses: actions/setup-node@v4
  #      with:
  #        node-version: '20'       # Précise sur quelle version de java le test est effectué
  #    - run: une commande          # Commande qui lance tout les tests unitaire
  #    - run: une autre commande    # 
