name: Build sample Java Maven project

on: [push, pull_request]

jobs:
  #compile:
    

  build:
    runs-on: ubuntu-20.04
    #needs: compile
    name: Build the Maven Project
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
          distribution: 'adopt'
          java-version: '20'
          java-package: jdk
    - name: Build and test project
      run: mvn -B clean install && javadoc -d doc -sourcepath projet/src/main/java/Joubert_Mineau_Sauzeau_Sube/*.java


