name: actions

run-name: test de compilation

on:
  push:
    branches:
      ignore: '**'  # ignore tous les push sur toutes les branches
  schedule:
    - cron: '0 0 * * *'  # exécute une fois par jour à minuit (UTC)
jobs:
  compile-projet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          #settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      #- name: Publish to GitHub Packages Apache Maven
      #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
  # exemple (ne pas supprimé)
  #nom-du-job:
  #  runs-on: image-os
  #  steps:
  #    - uses: actions/checkout@v4  #Ne pas changer ça 
  #    - uses: actions/setup-node@v4
  #      with:
  #        node-version: '20'       # Précise sur quelle version de java le test est effectué
  #    - run: une commande          # Commande qui lance tout les tests unitaire
  #    - run: une autre commande    # 
